name: PKGBUILDCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pkgbuild_job:
    runs-on: ubuntu-latest
    name: A job to perform pkgbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Arcadia PKGBUILDs
        id: build-pkg
        uses: ArcadiaLinux/arcadia-makepkg@v1.3
        with:
          path: "/github/workspace/arcadia-i3-config"
